### ISSUE TITLE
Unexpected crash when calling delete()

### ISSUE THREAD

**Issue by unstubbable** [mabels/wasm-icu#4]
![Screen Shot 2019-09-24 at 12 25 53](https://user-images.githubusercontent.com/761683/65504434-3fb20400-dec7-11e9-939e-fe52f4c6df18.png)

The above crash probably occurred when our application, after recovering from a fetch error, tried to call `.delete()` on a `NumberFormat` instance.

**Comment by mabels** [comment]
How critical is this?
I would like to look into next week?

**Comment by unstubbable** [comment]
I’ve only seen this locally. So no hurry (yet), enjoy your vacation.

**Comment by unstubbable** [comment]
This crash was not caused by the delete call. The real reason was an unhandled promise rejection due to incorrect use of `Promise.all` like this one:

<img width="1368" alt="Screen Shot 2019-11-06 at 21 53 01" src="https://user-images.githubusercontent.com/761683/68337259-66777300-00e0-11ea-8f11-5ba8fe7daad3.png">

In `WasmIntlBinding.js` there is this code: `process["on"]("unhandledRejection",abort)` which results in the program being exited. I'm not sure whether `wasm-intl` should behave differently here. What do you think?

**Comment by mabels** [comment]
i will try to disable this: 
https://github.com/emscripten-core/emscripten/issues/7855

**Comment by mabels** [comment]
I make a new minor version with this option on:
Here is the regression test:
```
test("is wasmintl binding registered", async () => {
  const my = jest.fn();
  process.on('unhandledRejection', my);
  process.emit('unhandledRejection' as any, 'Hello', 'World');
  process.removeListener('unhandledRejection', my);
  expect(my).toEqual({doof:1});
});
```
